name: Docker Image CI

on:
  workflow_dispatch:    
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 13 * * 1"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      versionX: $(date -u +%Y%m%d%H%M%S)
      version: latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ormico/sqlpackage:${{ github.sha }}
            ormico/sqlpackage:$(date -u +'%Y%m%d%H%M%S')
