name: Docker Image CI

on:
  workflow_dispatch:
    
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 13 * * 1"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      versionX: $(date -u +%Y%m%d%H%M%S)
      version: latest
    steps:
    - uses: actions/checkout@v2
    - name: echo
      run: echo $versionX
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ormico/sqlpackage:$versionX
    - name: Tag the Docker image
      run: docker tag ormico/sqlpackage:$versionX ormico/sqlpackage:$version
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: push the Docker image
      run: docker push ormico/sqlpackage:$versionX
    - name: push the Docker image
      run: docker push ormico/sqlpackage:$version
